apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  namespace: dplm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: "local-path"