apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.Nport }}
      protocol: TCP
  selector:
    app: {{ include "myapp.name" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.servicePort }}
      targetPort: {{ .Values.postgresql.servicePort }}
      protocol: TCP
  selector:
    app: postgres